export interface StudentRecord {
  id: string;
  name: string;
  email: string;
  phone: string;
  class: string;
  rollNo: string;
  gender: "male" | "female" | "other";
  dob: string;
  guardian: string;
  guardianContact: string;
  address: string;
  joinDate: string;
  status: "active" | "inactive" | "graduated" | "transferred";
  academicYear: string;
  subjects: string[];
  attendance: number;
  grade: string;
  image?: string;
}

export const studentManagementData = {
  stats: {
    total: 500,
    active: 480,
    inactive: 12,
    graduated: 5,
    transferred: 3,
    male: 265,
    female: 235,
  },
  students: [
    {
      id: "s1",
      name: "Rahul Sharma",
      email: "rahul.sharma@edunexus.edu",
      phone: "+91 98765 43210",
      class: "Grade 6-A",
      rollNo: "2024001",
      gender: "male",
      dob: "2013-01-15",
      guardian: "Mr. Rajesh Sharma",
      guardianContact: "+91 98765 43000",
      address: "123, Residential Colony, Bangalore",
      joinDate: "2024-06-01",
      status: "active",
      academicYear: "2026-27",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Hindi"],
      attendance: 85,
      grade: "A",
    },
    {
      id: "s2",
      name: "Priya Patel",
      email: "priya.patel@edunexus.edu",
      phone: "+91 98765 43211",
      class: "Grade 6-A",
      rollNo: "2024002",
      gender: "female",
      dob: "2013-03-20",
      guardian: "Mrs. Meera Patel",
      guardianContact: "+91 98765 43001",
      address: "456, Green Park, Bangalore",
      joinDate: "2024-06-01",
      status: "active",
      academicYear: "2026-27",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Hindi"],
      attendance: 92,
      grade: "A+",
    },
    {
      id: "s3",
      name: "Amit Kumar",
      email: "amit.kumar@edunexus.edu",
      phone: "+91 98765 43212",
      class: "Grade 6-B",
      rollNo: "2024003",
      gender: "male",
      dob: "2013-07-10",
      guardian: "Mr. Suresh Kumar",
      guardianContact: "+91 98765 43002",
      address: "789, Lake View, Bangalore",
      joinDate: "2024-06-01",
      status: "active",
      academicYear: "2026-27",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Hindi"],
      attendance: 78,
      grade: "B+",
    },
    {
      id: "s4",
      name: "Neha Sharma",
      email: "neha.sharma@edunexus.edu",
      phone: "+91 98765 43213",
      class: "Grade 7-A",
      rollNo: "2023001",
      gender: "female",
      dob: "2012-09-05",
      guardian: "Mr. Ravi Sharma",
      guardianContact: "+91 98765 43003",
      address: "321, Royal Enclave, Bangalore",
      joinDate: "2023-06-01",
      status: "active",
      academicYear: "2026-27",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Hindi"],
      attendance: 90,
      grade: "A",
    },
    {
      id: "s5",
      name: "Vikram Singh",
      email: "vikram.singh@edunexus.edu",
      phone: "+91 98765 43214",
      class: "Grade 7-B",
      rollNo: "2023002",
      gender: "male",
      dob: "2012-11-25",
      guardian: "Mrs. Anita Singh",
      guardianContact: "+91 98765 43004",
      address: "654, Garden City, Bangalore",
      joinDate: "2023-06-01",
      status: "inactive",
      academicYear: "2025-26",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Hindi"],
      attendance: 65,
      grade: "C",
    },
    {
      id: "s6",
      name: "Ananya Reddy",
      email: "ananya.reddy@edunexus.edu",
      phone: "+91 98765 43215",
      class: "Grade 8-A",
      rollNo: "2022001",
      gender: "female",
      dob: "2011-05-12",
      guardian: "Mr. Krishna Reddy",
      guardianContact: "+91 98765 43005",
      address: "987, Park View, Bangalore",
      joinDate: "2022-06-01",
      status: "active",
      academicYear: "2026-27",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Computer Science"],
      attendance: 88,
      grade: "A-",
    },
    {
      id: "s7",
      name: "Arjun Nair",
      email: "arjun.nair@edunexus.edu",
      phone: "+91 98765 43216",
      class: "Grade 9-A",
      rollNo: "2021001",
      gender: "male",
      dob: "2010-08-18",
      guardian: "Mrs. Lakshmi Nair",
      guardianContact: "+91 98765 43006",
      address: "147, Heritage Apartments, Bangalore",
      joinDate: "2021-06-01",
      status: "active",
      academicYear: "2026-27",
      subjects: ["Mathematics", "Physics", "Chemistry", "English", "Biology"],
      attendance: 82,
      grade: "B+",
    },
    {
      id: "s8",
      name: "Kavya Menon",
      email: "kavya.menon@edunexus.edu",
      phone: "+91 98765 43217",
      class: "Grade 10-A",
      rollNo: "2020001",
      gender: "female",
      dob: "2009-03-22",
      guardian: "Mr. Mohan Menon",
      guardianContact: "+91 98765 43007",
      address: "258, Lake View Villa, Bangalore",
      joinDate: "2020-06-01",
      status: "graduated",
      academicYear: "2025-26",
      subjects: ["Mathematics", "Physics", "Chemistry", "English", "Biology"],
      attendance: 95,
      grade: "A+",
    },
    {
      id: "s9",
      name: "Rohan Das",
      email: "rohan.das@edunexus.edu",
      phone: "+91 98765 43218",
      class: "Grade 8-B",
      rollNo: "2022002",
      gender: "male",
      dob: "2011-12-01",
      guardian: "Mrs. Pooja Das",
      guardianContact: "+91 98765 43008",
      address: "369, Urban Nest, Bangalore",
      joinDate: "2022-06-01",
      status: "transferred",
      academicYear: "2025-26",
      subjects: ["Mathematics", "Science", "English", "Social Studies", "Computer Science"],
      attendance: 70,
      grade: "C+",
    },
  ] as StudentRecord[],
};