export interface SubjectRecord {
  id: string;
  code: string;
  name: string;
  category: "core" | "elective" | "vocational" | "co-curricular";
  grades: string[];
  teachers: string[];
  description: string;
  credits: number;
  periodsPerWeek: number;
  status: "active" | "archived" | "draft";
  textbooks: string[];
  syllabus: string;
  createdAt: string;
  updatedAt: string;
}

export const subjectManagementData = {
  stats: {
    total: 24,
    active: 20,
    archived: 2,
    draft: 2,
    core: 14,
    elective: 6,
    vocational: 2,
    coCurricular: 2,
  },
  subjects: [
    {
      id: "sub1",
      code: "MATH-101",
      name: "Mathematics",
      category: "core",
      grades: ["6", "7", "8", "9", "10"],
      teachers: ["Mrs. Sunita Sharma", "Dr. Anjali Kumar"],
      description: "Fundamental mathematics including algebra, geometry, and statistics",
      credits: 5,
      periodsPerWeek: 6,
      status: "active",
      textbooks: ["Mathematics Textbook Grade 6-10", "Algebra Workbook"],
      syllabus: "Comprehensive mathematics curriculum covering all major concepts",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-15",
    },
    {
      id: "sub2",
      code: "SCI-101",
      name: "Science",
      category: "core",
      grades: ["6", "7", "8", "9", "10"],
      teachers: ["Mr. Rajesh Verma", "Ms. Meera Reddy"],
      description: "Integrated science covering physics, chemistry, and biology",
      credits: 5,
      periodsPerWeek: 6,
      status: "active",
      textbooks: ["Science Textbook Grade 6-10", "Lab Manual"],
      syllabus: "Comprehensive science curriculum with practical labs",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-15",
    },
    {
      id: "sub3",
      code: "ENG-101",
      name: "English",
      category: "core",
      grades: ["6", "7", "8", "9", "10"],
      teachers: ["Mrs. Priya Rao"],
      description: "English language and literature studies",
      credits: 4,
      periodsPerWeek: 5,
      status: "active",
      textbooks: ["English Literature Grade 6-10", "Grammar Book"],
      syllabus: "Comprehensive English curriculum with literature focus",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-10",
    },
    {
      id: "sub4",
      code: "SOC-101",
      name: "Social Studies",
      category: "core",
      grades: ["6", "7", "8"],
      teachers: ["Mr. Arun Nair"],
      description: "History, geography, and civics education",
      credits: 4,
      periodsPerWeek: 4,
      status: "active",
      textbooks: ["Social Studies Textbook Grade 6-8"],
      syllabus: "Comprehensive social studies curriculum",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-05",
    },
    {
      id: "sub5",
      code: "HIN-101",
      name: "Hindi",
      category: "core",
      grades: ["6", "7", "8"],
      teachers: ["Mrs. Kavita Singh"],
      description: "Hindi language and literature",
      credits: 3,
      periodsPerWeek: 4,
      status: "active",
      textbooks: ["Hindi Textbook Grade 6-8"],
      syllabus: "Hindi language and literature curriculum",
      createdAt: "2023-06-01",
      updatedAt: "2025-12-20",
    },
    {
      id: "sub6",
      code: "PHY-101",
      name: "Physics",
      category: "core",
      grades: ["9", "10", "11", "12"],
      teachers: ["Mr. Rajesh Verma"],
      description: "Advanced physics concepts and applications",
      credits: 5,
      periodsPerWeek: 5,
      status: "active",
      textbooks: ["Physics Textbook Grade 9-12", "Physics Lab Manual"],
      syllabus: "Advanced physics curriculum with practical applications",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-20",
    },
    {
      id: "sub7",
      code: "CHEM-101",
      name: "Chemistry",
      category: "core",
      grades: ["9", "10", "11", "12"],
      teachers: ["Ms. Meera Reddy"],
      description: "Chemical principles and laboratory practices",
      credits: 5,
      periodsPerWeek: 5,
      status: "active",
      textbooks: ["Chemistry Textbook Grade 9-12", "Chemistry Lab Manual"],
      syllabus: "Advanced chemistry curriculum with lab work",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-18",
    },
    {
      id: "sub8",
      code: "BIO-101",
      name: "Biology",
      category: "core",
      grades: ["9", "10"],
      teachers: ["Ms. Meera Reddy"],
      description: "Life sciences and biological systems",
      credits: 4,
      periodsPerWeek: 4,
      status: "active",
      textbooks: ["Biology Textbook Grade 9-10"],
      syllabus: "Biology curriculum covering life sciences",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-12",
    },
    {
      id: "sub9",
      code: "CS-101",
      name: "Computer Science",
      category: "elective",
      grades: ["8", "9", "10", "11", "12"],
      teachers: ["Mr. Suresh Patel"],
      description: "Computer programming, web development, and AI fundamentals",
      credits: 4,
      periodsPerWeek: 4,
      status: "active",
      textbooks: ["Computer Science Textbook", "Programming Guide"],
      syllabus: "Comprehensive computer science curriculum",
      createdAt: "2023-06-01",
      updatedAt: "2026-02-01",
    },
    {
      id: "sub10",
      code: "MATH-201",
      name: "Advanced Mathematics",
      category: "elective",
      grades: ["11", "12"],
      teachers: ["Dr. Anjali Kumar"],
      description: "Advanced mathematics for higher secondary students",
      credits: 5,
      periodsPerWeek: 6,
      status: "active",
      textbooks: ["Advanced Mathematics Grade 11-12"],
      syllabus: "Advanced mathematics curriculum for grades 11-12",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-20",
    },
    {
      id: "sub11",
      code: "ECO-101",
      name: "Economics",
      category: "elective",
      grades: ["11", "12"],
      teachers: ["Mr. Amit Gupta"],
      description: "Economics principles and applications",
      credits: 4,
      periodsPerWeek: 4,
      status: "draft",
      textbooks: ["Economics Textbook Grade 11-12"],
      syllabus: "Economics curriculum for higher secondary",
      createdAt: "2025-08-01",
      updatedAt: "2025-12-01",
    },
    {
      id: "sub12",
      code: "ART-101",
      name: "Fine Arts",
      category: "co-curricular",
      grades: ["6", "7", "8"],
      teachers: ["Mrs. Shobha Menon"],
      description: "Creative arts including painting, drawing, and sculpture",
      credits: 2,
      periodsPerWeek: 2,
      status: "active",
      textbooks: ["Art Textbook"],
      syllabus: "Creative arts curriculum",
      createdAt: "2023-06-01",
      updatedAt: "2025-12-10",
    },
    {
      id: "sub13",
      code: "MUSIC-101",
      name: "Music",
      category: "co-curricular",
      grades: ["6", "7", "8"],
      teachers: ["Mr. David Thomas"],
      description: "Music theory and practical education",
      credits: 2,
      periodsPerWeek: 2,
      status: "archived",
      textbooks: ["Music Textbook"],
      syllabus: "Music education curriculum",
      createdAt: "2023-06-01",
      updatedAt: "2025-08-01",
    },
    {
      id: "sub14",
      code: "PHYSED-101",
      name: "Physical Education",
      category: "vocational",
      grades: ["6", "7", "8", "9", "10"],
      teachers: ["Mr. Kiran Kumar"],
      description: "Physical fitness, sports, and health education",
      credits: 2,
      periodsPerWeek: 3,
      status: "active",
      textbooks: ["Physical Education Textbook"],
      syllabus: "Physical education and sports curriculum",
      createdAt: "2023-06-01",
      updatedAt: "2026-01-05",
    },
    {
      id: "sub15",
      code: "WS-101",
      name: "Workshop Skills",
      category: "vocational",
      grades: ["8", "9"],
      teachers: ["Mr. Prakash Reddy"],
      description: "Practical workshop skills and trades",
      credits: 2,
      periodsPerWeek: 3,
      status: "draft",
      textbooks: ["Workshop Skills Manual"],
      syllabus: "Vocational workshop skills curriculum",
      createdAt: "2025-10-01",
      updatedAt: "2026-01-15",
    },
  ] as SubjectRecord[],
};

export const gradeOptions = ["6", "7", "8", "9", "10", "11", "12"];
export const categoryOptions = [
  { value: "core", label: "Core" },
  { value: "elective", label: "Elective" },
  { value: "vocational", label: "Vocational" },
  { value: "co-curricular", label: "Co-Curricular" },
];
export const statusOptions = [
  { value: "active", label: "Active" },
  { value: "archived", label: "Archived" },
  { value: "draft", label: "Draft" },
];